# These are specific configuration settings required for travis-ci
language: ruby
before_script: "bundle exec rake appraisal:install"
script: "bundle exec rake appraisal"
rvm:
  - 1.9.3
  - 2.1.9
notifications:
  email: false