# These are specific configuration settings required for travis-ci
language: ruby
rvm:
  - 1.9.3
  - 2.1.5
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/rails_3.gemfile
